# ??? ActiveMQ ??????????????????????????????????????????????????????????????????
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# ??? Camel ?????????????????????????????????????????????????????????????????????
camel.springboot.main-run-controller=true
camel.springboot.name=MiniIntegrationPlatform

# ??? Common Queue Names ?????????????????????????????????????????????????????????
app.queue.core-entry=CORE.ENTRY.SERVICE.IN
app.queue.audit=COMMON.AUDIT.SERVICE.IN
app.queue.exception=COMMON.EXCEPTION.SERVICE.IN